Simple Backup and Restore
holochain/launcher pull request #166
Opened 2024-07-18 14:23 UTC by matthme

This PR is adds the backend functionality for a simple backup and restore mechanism:
- It adds a function that allows to backup all launcher data to a specified folder
- It adds a function to restore data from a folder of backup data

The idea is that the backup function may for example be called when the launcher is being quit and restoration from a backup could happen as part of the setup flow when starting with a new launcher from scratch.

This approach has amongst others the following limitations/drawbacks:
* It is heavy in data storage as it backs up almost all data
* The backed up data is not compressed into a single file as compression of this amount of data takes a long time and compression did not even seem to make the end-result considerably smaller
* The problem of the case where a device breaks while the launcher is running and the backup then only contains partial source chain data which could then lead to source chain forks when restoring from that backup is not solved

Backing up to and from different OS has been tested (Windows 10, macOS Catalina, Ubuntu 22.04) and seems to work fine.

2024-07-18 14:38 UTC, matthme commented
Side note - I think the practice that you started on scaffolding to get PR reviews from a broader circle of people is a good idea so I will experiment with adopting it here as well @c12i .

2024-07-18 14:42 UTC, mrruby requested changes

2024-07-18 14:42 UTC, mrruby commented on src/main/filesystem.ts
> +const BACKUP_LOG_FILENAME = 'backups.log';
can we move it to const.ts file?

2024-07-18 14:49 UTC, matthme commented on src/main/filesystem.ts
> +const BACKUP_LOG_FILENAME = 'backups.log';
Okay, moved :+1:

2024-07-18 14:54 UTC, mrruby commented on src/main/filesystem.ts
> +const BACKUP_LOG_FILENAME = 'backups.log';
Thank you!

2024-07-18 14:54 UTC, mrruby approved these changes

2024-07-18 17:20 UTC, c12i commented on src/main/filesystem.ts
> +    return undefined;
```suggestion
    if (!fs.existsSync(this.launcherConfigPath)) return;
    const configStr = fs.readFileSync(this.launcherConfigPath, 'utf-8');
    return JSON.parse(configStr) as LauncherConfig;
```

2024-07-18 17:20 UTC, c12i commented on src/main/filesystem.ts
> +    return undefined;
```suggestion
    if (!launcherConfig) return;
    return launcherConfig.backupLocation;
```

2024-07-18 17:20 UTC, c12i commented on src/main/filesystem.ts
> +    try {
Similar log as above `console.log('backing up lair...');` missing

2024-07-19 13:33 UTC, matthme commented on src/main/filesystem.ts
> +    return undefined;
should be addressed now.

2024-07-19 13:33 UTC, matthme commented on src/main/filesystem.ts
> +    return undefined;
addressed.

2024-07-19 13:33 UTC, matthme commented on src/main/filesystem.ts
> +    try {
added console log as well here

2024-07-22 09:51 UTC, c12i approved these changes

2024-07-22 12:05 UTC, merged