Feat/automatic updates UI
holochain/launcher pull request #233
Opened 2024-10-31 10:52 UTC by matthme

This PR improves the UI around automatic updates (issue https://github.com/holochain/launcher/issues/202) following Figma screens that were created a few weeks ago (not exactly 1:1 but quite similarly).

* it creates an "Updates" section in settings that only shows up if there is an update available
* it displays an orange dot on the settings gear if a new update is available
* it displays information about the update in the updates section like changelog, version number, release time and lets you download & install the update and restart launcher (with a loading indicator)

To test this PR:
* change the version field in the root level package.json to `0.400.0-rc.1`
* build the launcher executable locally with `yar build:build:mac-arm64` or `yarn build:linux`etc.
* start launcher and verify that it offers to update to the latest compatible release (at the time of writing `0.400.0-rc.2`)

2024-11-04 17:57 UTC, c12i requested changes

2024-11-04 17:57 UTC, c12i commented on src/renderer/src/routes/settings/(menu)/[slug]/components/LauncherUpdates.svelte
> +	// import { getModalStore } from '@skeletonlabs/skeleton';
Is this code still needed?

2024-11-04 17:57 UTC, c12i commented on src/renderer/src/routes/settings/(menu)/[slug]/components/LauncherUpdates.svelte
> +	// }
Same here?

2024-11-04 17:57 UTC, c12i commented on src/renderer/src/routes/settings/components/RegularMenu.svelte
> +	});
```suggestion
if (val.isSuccess && val.data && !menuEntries.map((entry) => entry.name).includes($i18n.t(LAUNCHER_UPDATES))) {
    menuEntries = [launcherUpdateMenuEntry, ...menuEntries];
}
```

2024-11-04 17:57 UTC, c12i commented on src/renderer/src/lib/helpers/other.ts
> +		.replaceAll('<h5>', '<h1 class="h5">')
Are these tags still supposed to be replaced with `h1`?

2024-11-18 09:05 UTC, matthme commented
Good points, thank you! I addressed them all.

2024-11-19 09:50 UTC, c12i approved these changes

2024-11-19 10:26 UTC, merged